# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20171020_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cortes_lectordecb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_corte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
